### ISSUE TITLE
Copies

### ISSUE THREAD

**Issue by wimmelstein** [mona12rst/java#1]
Copies is not a property of a (single) book, rather than a property of an object like a StockItem. That binds a book to the copies of a book that are in stock, or how many were in print.
And if a Book is composed of an Author and various properties like Publisher, shouldn't Publisher be a separate object?
Also, it would be nice to have a ToString override on Author as well.

The relationship between objects and a database is food for next lesson.

**Comment by mona12rst** [comment]
thank you for the feed back, I will fix those. @wimmelstein
